// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// Registry: a thread-safe hashmap from erlang_ref to void*.
//
// Refs are generated by BEAM (via make_ref/0) and shipped in request frames.
// They are opaque to the worker; we hash over their numeric word array and
// compare lexicographically for equality.
//
// Collision handling: separate chaining. Bucket count is a power of two for
// a fast modulo. With the per-pid resource cap (plan's Resource Governance
// section) keeping entries bounded, 256 buckets gives a comfortable load.

#ifndef ERLFDB_REGISTRY_H
#define ERLFDB_REGISTRY_H

#include <ei.h>
#include <pthread.h>
#include <stddef.h>

#define ERLFDB_REGISTRY_BUCKETS 256

typedef struct erlfdb_registry_node {
    erlang_ref key;
    void *value;
    struct erlfdb_registry_node *next;
} erlfdb_registry_node;

typedef struct {
    erlfdb_registry_node *buckets[ERLFDB_REGISTRY_BUCKETS];
    pthread_rwlock_t lock;
    size_t count;
} erlfdb_registry;

// Initialise a registry. Must be called before any other operation.
void erlfdb_registry_init(erlfdb_registry *r);

// Destroy all nodes, calling free_value(node->value) for each entry.
// Pass NULL to skip value cleanup.
void erlfdb_registry_destroy(erlfdb_registry *r, void (*free_value)(void *));

// Insert or replace. Returns 0 on success, -1 on allocation failure.
// On replacement, the old value is returned via *old_out (may be NULL).
int erlfdb_registry_put(erlfdb_registry *r, const erlang_ref *key, void *value,
                        void **old_out);

// Lookup. Returns the value, or NULL if not found.
void *erlfdb_registry_get(erlfdb_registry *r, const erlang_ref *key);

// Remove and return the value, or NULL if not found.
void *erlfdb_registry_remove(erlfdb_registry *r, const erlang_ref *key);

// Current entry count (approximate under concurrent access).
size_t erlfdb_registry_count(erlfdb_registry *r);

#endif // ERLFDB_REGISTRY_H
